### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 42704: publication "pub_test" does not exist

### ISSUE THREAD

**Issue by ssamsundar** [PgOutput2Json/PgOutput2Json#2]
**Describe the bug**
Error in replication listener. Waiting for 10 seconds...
      Npgsql.PostgresException (0x80004005): 42704: publication "pub_test" does not exist
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|232_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.Replication.ReplicationConnection.StartReplicationInternal(String command, Boolean bypassingStream, CancellationToken cancellationToken)+MoveNext()

**To Reproduce**
Source code and database table definitions to reproduce the behavior. Include details about RabbitMQ topology (exchanges, queue bindings) if applicable.

**Expected behavior**
Need to receive the replication data

**Error messages or screenshots**
      Npgsql.PostgresException (0x80004005): 42704: publication "pub_test" does not exist
         at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|232_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
         at Npgsql.Replication.ReplicationConnection.StartReplicationInternal(String command, Boolean bypassingStream, CancellationToken cancellationToken)+MoveNext()

**Further technical information:**
Severity: ERROR
          SqlState: 42704
          MessageText: publication "pub_test" does not exist
          Where: slot "pg2j_9cafd1dbeed342439d71158c76344dd9", output plugin "pgoutput", in the change callback, associated LSN 0/1A37100     
          File: pg_publication.c
          Line: 533
          Routine: get_publication_oid

**Additional context**

**Comment by ssamsundar** [comment]
Found the problem and resolved.

To Resolve this issue.

Need to create publication with following format

```
CREATE PUBLICATION {publicationName} FOR TABLE {tableName};
```

It would be better, if it is document about this step.

**Comment by enadzan** [comment]
Hi @ssamsundar - the step about creating the publication is documented in the [main readme file of the repository](https://github.com/PgOutput2Json/PgOutput2Json#create-publication). 

But, I agree, it's good to have some info in the TestWorker project too (it's added now as summary comment of the Worker class).
